<?xml version="1.0"?>
<package format="3">
  <name>adaptive_mission_mode</name>
  <version>0.0.1</version>
  <description>ROS 2 backend node for layered Adaptive Mission Mode.</description>
  <maintainer email="user@example.com">adaptive_mission_mode</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen3_cmake_module</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>px4_ros2_cpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
