<?xml version="1.0"?>
<package format="3">
  <name>fc_mission_reader</name>
  <version>0.1.0</version>
  <description>ROS 2 C++ node that downloads the full MAVLink mission stored in the flight controller and publishes/writes it as JSON.</description>
  <maintainer email="user@example.com">ghuy</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>ament_index_cpp</depend>
  <depend>mavlink</depend>

  <exec_depend>ros2launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
